name: Cypress Tests

on:
  push:
    branches:
      - main  # Adjust branch name
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21' # Ensure compatibility

    - name: Install Dependencies
      run: npm install

    - name: Start Development Server
      run: npm run dev &
      env:
        CI: true

    - name: Wait for Server to Start
      uses: jakejarvis/wait-for-it-action@v1
      with:
        url: 'http://localhost:5173'
        timeout: 60  # Adjust timeout if needed

    - name: Run Cypress Tests
      uses: cypress-io/github-action@v5
      with:
        record: false
        config-file: cypress.config.js  # Ensure this matches your config file
